name: Build and Test Learn Customer Microservice

on:
  pull_request:
    branches: [ "staging" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests on Java 17
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

        - name: Build with Maven
          run: mvn clean verify