name: Build and Test Learning Customer Microservice

on:
  pull_request:
    branches:
      - staging

jobs:
  build-test:
    name: Build and Test Learn Customer App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: docker/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Unit Tests
        #TODO need explore more
        run: mvn -B test --file pom.xml

      - name: Build Application
        run: |
          mvn clean
          #TODO need explore more
          mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/learningCustomerApi-snapshot:$(date +'%Y-%m-%d_%H-%M-%S')
