build-image:

  runs-on: ubuntu-latest
  needs: build

  steps:

    - uses: actions/checkout@v3

    - uses: actions/download-artifact@master
      with:
        name: jar-file
        path: app.jar

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set env
      run: echo "DATE=$(date +%s)" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/learning-customer-api:${{ env.DATE }}