name: Build and Deploy Learning Customer Microservice

on:
  push:
    branches:
      - staging

jobs:
  build-test:
    name: Build and Test Learn Customer App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: docker/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Unit Tests
        #TODO need explore more
        run: mvn -B test --file pom.xml

      - name: Build Application
        run: |
          mvn clean
          #TODO need explore more
          mvn -B package --file pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: actions/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/learningCustomerApi-snapshot:$(date +'%Y-%m-%d_%H-%M-%S')
