name: Build and Deploy Learning Customer Microservice

on:
  pull_request:
    branches:
      - staging

jobs:
  build-test:
    name: Build and Test Learn Customer App
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          TAG="snapshot-${GITHUB_SHA::7}"
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/learning-customer-api:$TAG .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/learning-customer-api:$TAG

